#pragma once

enum class TokenType {
    // Literals
    INTEGER_LIT, DECIMAL_LIT, STRING_LIT, CHAR_LIT, BOOLEAN_LIT, IDENTIFIER,

    // Keywords
    INTEGER, DECIMAL, CHARACTER, STRING, BOOLEAN, ARRAY, ARRAY2D, LET,
    FOR, FROM, TO, DURING, IF, ELSE, RETURN,
    AND, OR, NOT,
    DISPLAY, DISPLAYLN, ENTER,

    // Operators
    PLUS, MINUS, STAR, SLASH, PERCENT, CARET,
    EQUAL_EQUAL, BANG_EQUAL, LESS, LESS_EQUAL, GREATER, GREATER_EQUAL,
    EQUAL,

    // Punctuation
    LEFT_PAREN, RIGHT_PAREN,
    LEFT_BRACKET, RIGHT_BRACKET,
    LEFT_BRACE, RIGHT_BRACE,
    COMMA, SEMICOLON,

    // Special
    EOF_TOKEN, INVALID
};
